### ISSUE TITLE
cordovaRedirectUri not working

### ISSUE THREAD

**Issue by EvansMatthew97** [remotestorage/remotestorage.js#1097]
Hello there

I am experiencing an issue with Cordova: it doesn't use the cordovaRedirectUri and instead uses the file:// path of the app (resulting in an error 400).

I have tried using
```ts
let remoteStorage = new RemoteStorage({
    ...
    cordovaRedirectUri: 'https://my.app.co.za'
});
```
And 
```ts
remoteStorage.setCordovaRedirectUri('https://my.app.co.za');
```
Where "my.app.co.za" is my own server's subdomain.

All code is running after cordova platform is ready, and window.cordova definitely exists. I have the in-app browser plugin installed. I'm currently running cordova@6.2.3.

The way I am connecting DropBox is as follows:
```ts
remoteStorage.dropbox.connect();
```

Any suggestions? Thanks

**Comment by skddc** [comment]
Hi. Great to see someone trying out Dropbox with Cordova!

Unfortunately, we didn't actually implement the Cordova support for the additional backends yet. As you can see in [this line](https://github.com/remotestorage/remotestorage.js/blob/master/src/dropbox.js#L212), it's just using the current URL instead of the configured Cordova one, in case it exists.

@galfert is working on new Cordova docs, which will include a note on this.

If you or someone else wants to give implementing this a try (should be easy; basically just change that URL in case there's a Cordova redirect URI configured, and maybe do it centrally in `authorize.js`), that'd be great! If not, a core dev will take care of it soon.

**Comment by MrPutuLips** [comment]
Fixed by #1099

**Comment by skddc** [comment]
Thanks!

Let's keep the issue open until it's actually merged. So others can still find it, while it's not fixed in `master`.
