### ISSUE TITLE
"e.local.closeDB is not a function"

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.js#874]
In `r.IndexedDB._rs_cleanup` from our production log. Unfortunately no source map available.

**Comment by skddc** [comment]
@galfert Could it be that this was fixed in your latest PR?

**Comment by galfert** [comment]
I didn't fix this explicitly, but it's possible that this error might have resulted due to one of the other problems I have fixed. But I'm not 100% sure about this.

**Comment by skddc** [comment]
Let's check how often we saw it since then.

**Comment by galfert** [comment]
I couldn't find it at all in our exception tracker.

**Comment by skddc** [comment]
On the "closed" pile it goes then. :)
